---

#
### CONTAINERS - DOCKER ###
#
# Docker containers installation.

- name: Install Docker Apt repository
  apt_repository:
    repo: "{{ docker_repository }}"
    state: present
    update_cache: yes
  become: yes

- name: Install Docker Apt repository key
  apt_key:
    id: "{{ docker_repository_key_id }}"
    data: "{{ docker_repository_key }}"
    state: present
  become: yes


- name: Install packages
  apt:
    pkg: "{{ item }}"
    force: yes
    install_recommends: no
    state: latest
  with_items:
    - docker-engine
  environment: "{{ proxy_env }}"
  become: yes

# vim: set ts=2 sts=2 sw=2 et:
