---

- hosts: master
  roles:
    - {
        role: installation-setup,
        tags: ['installation-setup']
    }
    - {
        role: basic-system,
        tags: ['basic-system']
    }
    - {
        role: role-master,
        tags: ['role-master']
    }
    - {
        role: service-containers,
        tags: ['service-containers']
    }

# vim: set ts=2 sts=2 sw=2 et:
